### ISSUE TITLE
Performance comments on mm_interactive

### ISSUE THREAD

**Issue by gaow** [rfeng2023/mmcloud#102]
Still seems slow --- about 150Kb per sec download when running `pixi-mamba.sh` to install pixi-mamba. Sometimes this even drops to 40Kb. In contrast, when running `mm_interactive.sh` without `--mount-packages` and install directly into the VM it is as fast as on a local machine (<5 min)

```
    validate cache       54 packages in 35s 194ms
  ⠒ download & extract   [00:01:45] [━━━━━━━━━━━━━━━━━───] 53.09 MiB @ 188.51 KiB/s awscli (+1)
  ⠐ installing packages  [00:01:46] [━━━━━━━━━━━━━━━━━━━─]    54/57                                                                                                                                          ⠈ creating virtual environment
    validate cache       56 packages in 2m 17s 884ms
  ⠤ download & extract   [00:02:55] [━━━━━━━━━━━━━━━━━━──] 56.85 MiB @ 140.69 KiB/s awscli
  ⠈ installing packages  [00:02:56] [━━━━━━━━━━━━━━━━━━━─]    54/57 python (+1)  
```

It seems there is still room to improve. We can also try to trim some packages. For example, `awscli` is a large package that takes 6.5 minutes to download. Do we need `awscli` in our VM at all?

**Comment by Ashley-Tung** [comment]
By default, all MMC instances will have access to the awscli within the container via `https://tmate.io/t/ZGFceuedpcCjZz29hqGeADVmM`
So yes, we can get rid of the awscli that is installed in the installation script
![image](https://github.com/user-attachments/assets/2a59c09d-fcaa-4206-98f5-e131a26d6eb0)

**Comment by gaow** [comment]
I think this is also resolved now that we have tested out EFS.
