### ISSUE TITLE
Collect and prompt users about their existing interactive sessions

### ISSUE THREAD

**Issue by gaow** [rfeng2023/mmcloud#110]
@Ashley-Tung I wonder if we can add in the mm_interactive.sh this check: if we can see in the current opcenter, there are other jobs that are either 

1. under the same job name as the one to be submitted;
2. the job name contains `tmate`
3. for 1 and 2 they are either running or suspended

Then we should give a warning printed in red text to the user that they may have duplicated jobs already running on the cloud? Thsi will help us cutting the bills further. 

The current script will have default job name as `userid_ide_port` . I want to specifically track `tmate` is because `tmate` session is only kind of intented for the initial setup. Even of people want to have a command session later they should use the JupterLab IDE for the command line.

**Comment by Ashley-Tung** [comment]
Yes, this can be done! To further develop the decision tree, we can do:
* If the user does decide to name the interactive job, we can still keep track of `user_ide_port`
* When the float submit command is generated (not yet submitted),
    * If job name has `tmate`, warn user about it intended to be for initial setup. User has to approve to continue with submission
    * If the job name already exists (will need to search for this), warn user. User has to approve to continue with submission
    * If there is *at least one* interactive job running/suspended (need to search for this and determine how we would know it's an interactive job - probably by image?), warn user. User has to approve to continue with submission

**Comment by gaow** [comment]
Sounds great @Ashley-Tung . All these are very nice engineering considerations. For the last item, 

> If there is at least one interactive job running/suspended (need to search for this and determine how we would know it's an interactive job - probably by image?), warn user. User has to approve to continue with submission

This is a bit tricky since in the future, we might even consider using this image for batch jobs. WE don't see any reaons we cannot do that. 

So I would suggest we skip this last item only stick t othe first two. As you said you can track `user_ide_port` I guess via something like `customized_job_name.user_ide_port` if customized names are given right? Then we just compare the `user_ide_port` part by spliting with `.` and take the last piece if applicable. Then we proceed with your proposed 1 and 2? Then our job name search will be based strictly on `user_ide_port`.

**Comment by Ashley-Tung** [comment]
If the user commits to just submitting their interactive job as `user_ide_port`, we can just use that format to search

**Comment by gaow** [comment]
> If the user commits to just submitting their interactive job as user_ide_port, we can just use that format to search
Not sure what this means ... the users can put in any job_name using `-jn` right? I think you proposed that we somehow should also be able to track it if users change the default job names and my proposal is to always append `user_ide_port` at the job name and search for this pattern anywyas.

**Comment by Ashley-Tung** [comment]
Sorry, let me correct myself.
What I meant in "we can still keep track of `user_ide_port`", this was within `mm_interactive` itself. But if we just always append `user_ide_port` to the end of the job name, even when there is a unique name, this will cover the case anyway

**Comment by Ashley-Tung** [comment]
I can get to work on this today

**Comment by Ashley-Tung** [comment]
I have updated the scripts and done some tests. Below are screenshots

1. Submitting a tmate job, will warn user
![image](https://github.com/user-attachments/assets/28775016-82d8-4526-8c2e-be61da680fda)

2. Submitting a second job (new name) when there is an existing executing job with the same ide
![image](https://github.com/user-attachments/assets/64b25c96-9af8-4244-b920-c6423eb2c381)

PR: https://github.com/rfeng2023/mmcloud/pull/112

**Comment by gaow** [comment]
Perfect thank you @Ashley-Tung for the quick nice work
