### ISSUE TITLE
Inability to restart jupyter-lab session in a VM 

### ISSUE THREAD

**Issue by gaow** [rfeng2023/mmcloud#114]
When something goes wrong in a Jupter Lab session and crashed it, the only way to fix it is to start a new VM. This is different from when we run on a local machine if `jupyter-lab` crashes we kill this instance (`Ctrl-c`) and start a new one. Here by using `-de juptyer` we are stuck on the entrypoint of the `jupyter-lab` command at the start of the VM. We don't get a chance to restart it without having to restart the VM.

**Comment by gaow** [comment]
One possible way out is we always enter a `tmate` session and trigger `jupyter-lab` from there. But the issue is according to @rl3328 the baseline resource usage is obviously higher compared to another session with just jupter-lab.

**Comment by Ashley-Tung** [comment]
The baseline resource usage is higher if running tmate -> jupyter-lab than just jupyter-lab?

**Comment by Ashley-Tung** [comment]
I am wondering if the `bind_mount` script can also be changed to include: if the command `jupyter-lab` (or equivalent) returns a non-zero error code, run it again

**Comment by gaow** [comment]
> The baseline resource usage is higher if running tmate -> jupyter-lab than just jupyter-lab?

anecdotally yes. This is espeically tricky whne people are on a 16GB instance but the base system takes a lot of it. 

> bind_mount script can also be changed to include: if the command jupyter-lab (or equivalent) returns a non-zero error code, run it again. 

this is interesting --- like try to automatically restart it if it crashes? That would be nice.

**Comment by Ashley-Tung** [comment]
Yeah, it would look something like this. Let me know what you think
```
case "${VMUI}" in
  jupyter|jupyter-lab)
    if is_available jupyter-lab; then
      echo "JupyterLab is available. Starting JupyterLab ..."
      while true; do
          jupyter-lab
          # Check if jupyter-lab exited with a non-zero exit code
          if [ $? -ne 0 ]; then
              echo "Jupyter Lab crashed, restarting..."
          else
              echo "Jupyter Lab exited normally."
              break
          fi
          # Optionally, add a short sleep to avoid immediate retries
          sleep 30s
      done
    else
      echo "JupyterLab is not available."
      start_terminal_server
    fi
    ;;
```

**Comment by gaow** [comment]
looks good @Ashley-Tung . We can have the sleep to be 15 seconds or something --- just think when something crashes on you, how long would you patiently wait for it to come back :D

**Comment by Ashley-Tung** [comment]
Sounds good, i can implement it. However, it is difficult for me to intentionally test a crash, but ideally, since the instance considers the job to have failed if jupyter crashed (when ide is jupyter), this would catch it.

**Comment by gaow** [comment]
thanks @Ashley-Tung  let's see how it works for people.
