### ISSUE TITLE
`--download-include`  does not work 

### ISSUE THREAD

**Issue by rfeng2023** [rfeng2023/mmcloud#18]
```
./src/mm_jobman.sh \
./test_command.chr1.sos_splited_script2 \
 -c 2 -m 16 \
 --job-size 100 \
 --mount statfungen/ftp_fgc_xqtl:/home/$username/data \
         statfungen/ftp_fgc_xqtl/sos_cache/$username:/home/$username/.sos \
         statfungen/ftp_fgc_xqtl/analysis_result/finemapping_twas:/home/$username/output \
 --mountOpt "mode=r" "mode=rw" "mode=rw" \
 --cwd "/home/$username/data" \
 --image ghcr.io/cumc/pecotmr_docker:latest \
 --entrypoint "source /usr/local/bin/_activate_current_env.sh" \
 --env ENV_NAME=pecotmr \
 --imageVolSize 10 \
 --opcenter 54.81.85.209 \
 --download "statfungen/ftp_fgc_xqtl/ROSMAP/genotype/analysis_ready/geno_by_chrom/:/home/$username/input" \
 --recursive true \
 --ebs-mount "/home/$username/input=60" \
--no-fail-fast  --download-include ROSMAP_NIA_WGS.leftnorm.bcftools_qc.plink_qc.1.bed ROSMAP_NIA_WGS.leftnorm.bcftools_qc.plink_qc.1.bim ROSMAP_NIA_WGS.leftnorm.bcftools_qc.plink_qc.1.fam
```
Hi @Ashley-Tung , we are using this command to submit job, which I think should download  `ROSMAP_NIA_WGS.leftnorm.bcftools_qc.plink_qc.1.bed`, `ROSMAP_NIA_WGS.leftnorm.bcftools_qc.plink_qc.1.bim`, `ROSMAP_NIA_WGS.leftnorm.bcftools_qc.plink_qc.1.fam` only with `--download-include` , but it seems downloaded everything in `statfungen/ftp_fgc_xqtl/ROSMAP/genotype/analysis_ready/geno_by_chrom/`. 

Is there anything wrong?

**Comment by Ashley-Tung** [comment]
Hi @rfeng2023 , the way that `--download-include` works is that it's only going to take in one filter for the include. So something like `--download-include ROSMAP_NIA_WGS.leftnorm.bcftools_qc.plink_qc.1.*` would work.

What job id was this for, so that I may take a look?

**Comment by Ashley-Tung** [comment]
Hi @rfeng2023 , try putting your `--download-include` commands in quotations

Additionally, what job id is this for so that I may take a look?

**Comment by Ashley-Tung** [comment]
So like 
```
--download-include 'ROSMAP_NIA_WGS.leftnorm.bcftools_qc.plink_qc.1.bed ROSMAP_NIA_WGS.leftnorm.bcftools_qc.plink_qc.1.bim ROSMAP_NIA_WGS.leftnorm.bcftools_qc.plink_qc.1.fam'
```

**Comment by rfeng2023** [comment]
> Hi @rfeng2023 , try putting your `--download-include` commands in quotations
> 
> Additionally, what job id is this for so that I may take a look?

Thanks! that's kypqy1a3j177x8bx69x19

**Comment by rfeng2023** [comment]
I tried to use` --download-include ROSMAP_NIA_WGS.leftnorm.bcftools_qc.plink_qc.1.` in z6p2iljibzeu8jqcpx41c
and `--download-include 'ROSMAP_NIA_WGS.leftnorm.bcftools_qc.plink_qc.1.bed ROSMAP_NIA_WGS.leftnorm.bcftools_qc.plink_qc.1.bim ROSMAP_NIA_WGS.leftnorm.bcftools_qc.plink_qc.1.fam' `in earniqzy8v8kx6po6xgqp. None of them works

**Comment by Ashley-Tung** [comment]
So for z6p2iljibzeu8jqcpx41c, your entire download command ends up becoming 
```
aws s3 cp s3://statfungen/ftp_fgc_xqtl/ROSMAP/genotype/analysis_ready/geno_by_chrom/ /home/admin/input --recursive --include ROSMAP_NIA_WGS.leftnorm.bcftools_qc.plink_qc.1.
```
Because you did not a a `*` at the end, the command will look for a file exactly called `ROSMAP_NIA_WGS.leftnorm.bcftools_qc.plink_qc.1.`

So when trying to match multiple files with a wildcard, try `--download-include ROSMAP_NIA_WGS.leftnorm.bcftools_qc.plink_qc.1.*`

**Comment by Ashley-Tung** [comment]
For earniqzy8v8kx6po6xgqp, your download command is
```
aws s3 cp s3://statfungen/ftp_fgc_xqtl/ROSMAP/genotype/analysis_ready/geno_by_chrom/ /home/admin/input --recursive --include ROSMAP_NIA_WGS.leftnorm.bcftools_qc.plink_qc.1.bed --include ROSMAP_NIA_WGS.leftnorm.bcftools_qc.plink_qc.1.bim --include ROSMAP_NIA_WGS.leftnorm.bcftools_qc.plink_qc.1.fam
```

What was the issue here again? It is downloading the entire folder?

I did a test on my end with a test bucket like this:
```
[ec2-user@ip-172-31-27-61 ~]$ aws s3 cp s3://jfs-spotonly/pipeline_info/ /home/ec2-user/test --recursive --include execution*
download: s3://jfs-spotonly/pipeline_info/pipeline_dag_2023-10-24_22-13-22.html to test/pipeline_dag_2023-10-24_22-13-22.html
download: s3://jfs-spotonly/pipeline_info/execution_trace_2023-10-24_22-13-22.txt to test/execution_trace_2023-10-24_22-13-22.txt
download: s3://jfs-spotonly/pipeline_info/execution_timeline_2023-10-24_22-13-22.html to test/execution_timeline_2023-10-24_22-13-22.html
download: s3://jfs-spotonly/pipeline_info/execution_report_2023-10-24_22-13-22.html to test/execution_report_2023-10-24_22-13-22.html
```
As you can see, even though I used `--include 'execution*'` with the intention to only copy files that start with `execution*`, I still have a file copied starting with `pipeline`

This is due to a misinterpretation of `--include` on my part, which does not mean "Only include", it just means "Don't exclude"

To fix this, adding a `--exclude "*"` in the beginning makes it so you include only certain files
```
[ec2-user@ip-172-31-27-61 ~]$ aws s3 cp s3://jfs-spotonly/pipeline_info/ /home/ec2-user/test --recursive --exclude "*"  --include "execution*"
download: s3://jfs-spotonly/pipeline_info/execution_trace_2023-10-24_22-13-22.txt to test/execution_trace_2023-10-24_22-13-22.txt
download: s3://jfs-spotonly/pipeline_info/execution_timeline_2023-10-24_22-13-22.html to test/execution_timeline_2023-10-24_22-13-22.html
download: s3://jfs-spotonly/pipeline_info/execution_report_2023-10-24_22-13-22.html to test/execution_report_2023-10-24_22-13-22.html
```

This is also a method mentioned by the documentation: https://docs.aws.amazon.com/cli/latest/reference/s3/#use-of-exclude-and-include-filters

Knowing this, @gaow do you think we can add this change to our include commands?

**Comment by Ashley-Tung** [comment]
@rfeng2023 , once you can confirm the latest PR addresses this issue, please close it. Thanks!

**Comment by rfeng2023** [comment]
@Ashley-Tung sure, thanks!
