### ISSUE TITLE
Better parallelization via `parallel`

### ISSUE THREAD

**Issue by gaow** [rfeng2023/mmcloud#20]
Suppose we have 6 commands to run. In our current setting, we specify `--parallel-commands 3` then under the hood we implement it as:

```
parallel ::: cmd1 cmd2 cmd3
parallel ::: cmd4 cmd5 cmd6
```

the issue with this implementation is that the 2nd line have to wait until the first line to finish before it starts. So when 2 out of the 3 commands in the first line finishes and the 3rd one drags long time, it's going to block other commands from kicking in. This is why we often see a EKG shaped wavewatcher plot:

![image](https://github.com/rfeng2023/mmcloud/assets/917985/7495fac0-c607-4863-9c13-cf374a3dbe3f)

To fully use all the resources without seeing any of the valleys in the usage, it seems to make sense to do this:

```
parallel -j 3 ::: cmd1 cmd2 cmd3 cmd4 cmd5 cmd6
``` 

instead. If you look into parallel documentation i believe this is the right thing to do. That will make our executions more resource efficient. We should basically see that memory stays at high usage any time. 

Any thoughts?

**Comment by Ashley-Tung** [comment]
I think this is a better, and even easier way to implement the parallel command! We will be focusing just on the `--parallel-commands` parameter to implement this

**Comment by Ashley-Tung** [comment]
Cases I have tested:

* One command in the job script
    * No matter the value of `job-size` or `parallel-commands`, the command submitted will not have the `parallel` keyword
    ```
    {
    while IFS= read -r command; do
        eval $command || true
    done <<< '''"sos run my_pipeline.sos --gene APOE4"'''
}
```
* Six commands in the job script
    * Job size 6, parallel commands 1
        * all commands in the submitted script, but no `parallel` keyword, as all commands run on their own
        ```
        {
    while IFS= read -r command; do
        eval $command || true
    done <<< '''"sos run my_pipeline.sos --gene APOE4" "sos run my_pipeline.sos --gene BIN1" "sos run my_pipeline.sos --gene TREM2" "sos run my_pipeline.sos --gene APOE4" "sos run my_pipeline.sos --gene BIN1" "sos run my_pipeline.sos --gene TREM2"'''
}
```
    * Job size 6, parallel command 3
        * All commands are in the submitted script, but with `parallel -j 3`
        ```
        {
    while IFS= read -r command; do
        eval $command || true
    done <<< '''parallel -j 3 ::: "sos run my_pipeline.sos --gene APOE4" "sos run my_pipeline.sos --gene BIN1" "sos run my_pipeline.sos --gene TREM2" "sos run my_pipeline.sos --gene APOE4" "sos run my_pipeline.sos --gene BIN1" "sos run my_pipeline.sos --gene TREM2"'''
}
```

**Comment by Ashley-Tung** [comment]
* Job size 6, parallel command 3
        * All commands are in the submitted script, but with `parallel -j 3`
```
        {
    while IFS= read -r command; do
        eval $command || true
    done <<< '''parallel -j 3 ::: "sos run my_pipeline.sos --gene APOE4" "sos run my_pipeline.sos --gene BIN1" "sos run my_pipeline.sos --gene TREM2" "sos run my_pipeline.sos --gene APOE4" "sos run my_pipeline.sos --gene BIN1" "sos run my_pipeline.sos --gene TREM2"'''
}
```
