### ISSUE TITLE
Limit maximum number of CPU when submit

### ISSUE THREAD

**Issue by gaow** [rfeng2023/mmcloud#21]
`mm_jobman.sh` needs to support both minimum cores and maximum cores. By default we can use  `-c` for both minimum and maximum cores so we basically limit the machine type to exactly what we need. Then optionally we support `-c-max` to set the upper bound if there is a need.

This request is motivated by the fact that currently after we exhaust all the `2xlarge` machines, because no upper bound is set, mmcloud starts to ask eg 4xlarge, 8xlarge which is a waste of resource. We would rather wait for next available 2xlarge than to use them. 

Since `float` has this option already, all we need here is to add an interface to it.

**Comment by Ashley-Tung** [comment]
Hi @gaow, there are two ways you can limit how much cpu your instance will have. Both have the same functionality, but for two different reasons. (I will also put this as a comment for issue #21 for documentation)
* Per job
    * You can submit cpu specs in the form of float submit -c min_cpu:max_cpu
    * This gives a range of instances to look for when you are initializing your instance
        * This does not apply to Waveriding/changing instances due to cpu utilization. This only applies to creating a new instance + floating due to instance interruption
    * Implementing this would require an update to mm_jobman but not too much
*Per OpCenter
    * You can see in the screenshot attached you can limit the cpus of your instance this way
    * However, this only applies in the case of WaveRiding. If OpCenter determines waveriding is needed, it will disregard your min_cpu:max_cpu and rely on the upper and lower limits given in the settings
    * Implementing this is just a settings change that will apply to all jobs that need waveriding
    
![image](https://github.com/rfeng2023/mmcloud/assets/52087355/022c1e77-178b-417a-a7b0-c456f8801a48)

Knowing this, let me know which method you would like to go with.

**Comment by gaow** [comment]
As discussed the mm_jobman command now supports max and min CPUs. We have disabled on our opcenter the CPU triggered migrate for the current analysis tasks.
