### ISSUE TITLE
More informative job summary

### ISSUE THREAD

**Issue by gaow** [rfeng2023/mmcloud#28]
Currently, on the left side of the opcenter job status summary it says in blue something like "Running: 130 of 491 Total". The number 130 is informative, but the 491 is not. It would be more informative to summarize how many are submitted (queued), how many are running (including initializing, starting and executing), how many are floating. We don't need total because on the cost summary page we will find how many jobs were executed in the opcenter anyways. 

What do you think? @Ashley-Tung

**Comment by Ashley-Tung** [comment]
Currently, we do not support summarizing currently running jobs with multiple status filters. Would you like me to submit a Feature Request to our engineering team for this?

**Comment by gaow** [comment]
Yes @Ashley-Tung please let them consider if it is reasonable. The proposed message is `## running, ## floating and ## submitted.`

**Comment by gaow** [comment]
Already improved in updated opcenter
