### ISSUE TITLE
Prioritize on the VM instances to use

### ISSUE THREAD

**Issue by gaow** [rfeng2023/mmcloud#34]
Within the AWS r5, r6 and r7 families, when i set -c and -m like this:

```
-c 2:16 -m 16:128
```

there will be 4 types of VM I can use:

1. 2 core 16 gb
2. 4 core 32 gb
3. 8 core 64 gb
4. 16 core 128 gb

Can i specify my preference of the VM I would like? for example I would like the VM to come in the order of 3 -> 2 -> 4 -> 1. That is, I want to find all available VM of specification 3, then if they are no longer available, I will look for VM 2, then VM 4 then finally VM 1. How to achieve it?

**Comment by Ashley-Tung** [comment]
Currently, there is no way to do this in MMC. MMC will always look for the cheapest instance available, given the constraints.

This is somewhat related to the issue I brought up with engineering, on how our current method for choosing instances will result in the cheapest one always being chosen, despite it not being available (also relates to your issue #35 a little). I will bring this up with engineering to see if this is viable

**Comment by gaow** [comment]
Close it because as other bugs are fixed this becomes less relevant.
