### ISSUE TITLE
Set up new opcenter

### ISSUE THREAD

**Issue by gaow** [rfeng2023/mmcloud#40]
Need to make sure:

1. new opcenter has the correct imagepath
2. new opcenter has more cpu /memry (x-large) instance
3. new opcenter has 6-subnets in US-EAST-1 (a-f) so there is plenty of IP available

Additionally,

1. new opcenter can use configuration exported from old opcenter
2. new opcenter running latest float software
3. new opcenter can migrate the cost summary of the old one, if desired. 

We need documentaitons for all of them.

**Comment by Ashley-Tung** [comment]
Hi @gaow ,
1. Charlie will make sure the new opcenter points to an s3 bucket for its image path. This will likely solve the issue on "0 container" being found, as well as the timeout issue we are seeing. If it does not, we will do more investigating on our part, but it will eliminate a potential source of the issue
2. @rfeng2023 had a meeting with Charlie to confirm the new opcenter is x-large
3. @rfeng2023 had a meeting with Charlie to confirm the range of the subnets
4. I will be working on commands that reflect the system settings from the opcenter. It will be shared here shortly
5. Charlie will make sure the new opcenter uses the same private build as the old
6. This is a non-trivial task and will require more time and investigation on our side

**Comment by gaow** [comment]
List of configurations,

```
float config set cloud.createVMPolicy spotOnly
float config set cloud.createVMRetryInterval 5m0s
float config set cloud.createVMRetryLimit -1
float config set migrate.cpuLowerBoundDuration 10m0s
float config set migrate.cpuLowerBoundRatio 1
float config set migrate.cpuLowerLimit 8
float config set migrate.cpuMigrateStep 25
float config set migrate.cpuUpperBoundDuration 10m0s
float config set migrate.cpuUpperBoundRatio 99
float config set migrate.memDisable false
float config set migrate.memLowerBoundDuration 10m0s
float config set migrate.memLowerBoundRatio 1
float config set migrate.memLowerLimit 8
float config set migrate.memMigrateStep 25
float config set migrate.memUpperBoundDuration 5m0s
float config set provider.allowList r5*,r6*,r7*
float config set scheduler.jobExecutorLimit 900
```

this line:

```
float config set cloud.createVMRetryLimit -1
```

does not work due to bash syntax issue. We have to set it manually. Otherwise all works which is the current setup of our opcenter

**Comment by Bale4** [comment]
Two of the lines didn't work while I tried to update the west OpCenter on my iMAC `float config set cloud.createVMRetryLimit -1` (Error: unknown shorthand flag: '1' in -1`) and `float config set provider.allowList r5*,r6*` (zsh: no matches found: r5*,r6*)

**Comment by Ashley-Tung** [comment]
Is it another bash issue? try enclosing it in quotes or arrays?

**Comment by Bale4** [comment]
enclosing with quotes work for `float config set provider.allowList "r5*,r6*"`

**Comment by Ashley-Tung** [comment]
Updated configurations:
```
float config set cloud.createVMPolicy spotOnly
float config set cloud.createVMRetryInterval 5m0s
float config set cloud.createVMRetryLimit "-1"
float config set migrate.cpuLowerBoundDuration 10m0s
float config set migrate.cpuLowerBoundRatio 1
float config set migrate.cpuLowerLimit 8
float config set migrate.cpuMigrateStep 25
float config set migrate.cpuUpperBoundDuration 10m0s
float config set migrate.cpuUpperBoundRatio 99
float config set migrate.memDisable false
float config set migrate.memLowerBoundDuration 10m0s
float config set migrate.memLowerBoundRatio 1
float config set migrate.memLowerLimit 8
float config set migrate.memMigrateStep 25
float config set migrate.memUpperBoundDuration 10m0s
float config set provider.allowList "r5*,r6*,r7*"
float config set scheduler.jobExecutorLimit 900
float config ser cloud.handleRebalanceMemThreshold 128G
```
