### ISSUE TITLE
Data Upload Methods from S3 to Synapse

### ISSUE THREAD

**Issue by rfeng2023** [rfeng2023/mmcloud#53]
Currently, when attempting to transfer data from an S3 bucket to [Synapse](https://www.synapse.org/), there are a couple of methods available:

1. First, download the data to a local machine, then upload it to Synapse using the Command Line Interface (CLI).
2. Alternatively, launch a Jupyter notebook via Opcenter, employing either a bash notebook or a terminal kernel for the upload process. However, this approach has its drawbacks: the terminal kernel tends to be slow and prone to freezing, and utilizing a bash notebook for large tasks (such as uploading over 30,000 files) could lead to crashes due to interactive messages during the upload process.

There's also the possibility of directly linking the S3 bucket with Synapse by granting it 'ListObject' permissions, as outlined in the [synapse documentation](https://help.synapse.org/docs/Compute-Directly-on-Data-in-Synapse-or-S3.2048426057.html)). This raises several questions:

- Should we configure our bucket for this direct connection?
- What are the potential security implications?
- Could this incur additional costs?
- Are there more detailed guidelines available to ensure a smooth setup process?"

**Comment by gaow** [comment]
@rfeng2023 thanks for finding that solution. I would say we can work on moving data to NIAGADS AWS (free within East-1) then let NIAGADS figure out the ListObject stuff including potential cost and smoothing the process -- just have to work with their team to figure it out.

**Comment by Ashley-Tung** [comment]
Hi @rfeng2023 , I have reached out to engineering about implementing this as a feature request, as well as feedback on any other workaround we may find

This is for job id [fyt5k4sg5948c3s8oh6v9](https://23.22.157.8/#/opcenter/jobs/fyt5k4sg5948c3s8oh6v9)

@gaow do you think this could be solved by moving data to NIAGADS AWS? Or with moving to Columbia AWS per this message:
![image](https://github.com/rfeng2023/mmcloud/assets/52087355/afdd8108-f415-4839-ba7e-92305e73619f)

**Comment by Ashley-Tung** [comment]
Additionally, @rfeng2023 does this network graph line up with your usage? Did you test synapse during the time of peaks here:
![image](https://github.com/rfeng2023/mmcloud/assets/52087355/5fb5c86d-aae1-4b76-aaed-af91869973c5)

**Comment by gaow** [comment]
>do you think this could be solved by moving data to NIAGADS AWS?

@Ashley-Tung this is basically handing the problem to another group to let them take care of it. 

We are going to try either implementing the official suggestion from synapse or letting another group solve the issue.
