### ISSUE TITLE
(3/9/24 Jobs failed) - CRIU checkpointing failed -52

### ISSUE THREAD

**Issue by Ashley-Tung** [rfeng2023/mmcloud#62]
This Issue is to document the eight jobs that failed on 3/9 mentioned in this [slack message](https://memverge-support.slack.com/archives/C06GTN5RSCF/p1710112645687859)

They are:
* 1 Timed Out error
    * https://23.22.157.8/#/opcenter/jobs/m48zltsmblg2y1arzofcz
* 1 No Available Host error
    * https://23.22.157.8/#/opcenter/jobs/rzefr48cdf94aq3eqfrku
* 6 Failed to Complete Error
    * https://23.22.157.8/#/opcenter/jobs/ipu5oou8fjvad9xd60l4s
    * https://23.22.157.8/#/opcenter/jobs/pknwycf96amx3zp4c3gfy
    * https://23.22.157.8/#/opcenter/jobs/lel50qo5nar74bl1esfpx
    * https://23.22.157.8/#/opcenter/jobs/7nypi525gra8e7i3f5kcn
    * https://23.22.157.8/#/opcenter/jobs/nhp8zxsfh0taqe0detpku
    * https://23.22.157.8/#/opcenter/jobs/jkbzo4y7c529fiko0jius

All three have the error message in some form (or just a checkpointing error)
```
2024-03-10T18:45:48.717: Failed to checkpoint, error: Internal error: exit status 125, CRIU checkpointing failed -52.  Please check CRIU logfile /mnt/float-image/containers/storage/overlay-containers/56b718792d06fca99af26c37563a09c565c7edc967ec1747ab46830de29fa353/userdata/dump.log
Error: `/usr/bin/crun checkpoint --image-path /mnt/float-data/checkpoint --work-path /mnt/float-image/containers/storage/overlay-containers/56b718792d06fca99af26c37563a09c565c7edc967ec1747ab46830de29fa353/userdata --tcp-established --file-locks --link-remap --force-irmap --skip-in-flight --shell-job --ghost-limit 4294967295 56b718792d06fca99af26c37563a09c565c7edc967ec1747ab46830de29fa353` failed: exit status 1 (code: 1999). Abort recovering/wave-riding
```

Will be filing appropriate tickets to engineering on these 8 jobs and currently look into them

**Comment by Ashley-Tung** [comment]
[UPDATE]

The six jobs errors are due to the application itself stopped the checkpointing, as checkpointing reported the PID of the signal sender, which matched the PID of the application. The container has been updated so that this issue should no longer appear again.

For the first two jobs, they are part of a known CRIU checkpointing error that is expected to be patched in 2.5.1

**Comment by Ashley-Tung** [comment]
[UPDATE]
For the first two jobs mentioned above, the upgrading of our checkpointing engine will be delayed until 2.5.3

**Comment by gaow** [comment]
> upgrading of our checkpointing engine will be delayed until 2.5.3

@Ashley-Tung Approximately when is 2.5.3 to be released?

**Comment by Ashley-Tung** [comment]
Unknown for now, but it is coming up. 2.5.2 was just released, with the main feature update of visibility of OpCenter metric usage. This is useful in issues such as #57 , where the metrics could give us better insight into queue time

However, since we do not have the metrics for around the time issue #57 (I believe the screenshots Ru sent me from the AWS Console did not have all the data), I do not think we are able to find the cause of the issue until it happens again.

**Comment by Ashley-Tung** [comment]
[UPDATE]
The fix is currently in testing mode, thus did not make it to 2.5.3 update. Will let you know when it has been implemented

**Comment by gaow** [comment]
agreed!
