### ISSUE TITLE
Job Failed to restore exit status 125 (code: 9011)

### ISSUE THREAD

**Issue by Ashley-Tung** [rfeng2023/mmcloud#66]
Ticket currently submitted to Engineering

Error code 9011 - NOT due to `bad size` error from #61 

Example jobs: https://23.22.157.8/#/opcenter/jobs/94p4q13abcmadfgzpxi18

job.events:
```
2024-03-25T21:41:56.551: Requeue job 94p4q13abcmadfgzpxi18
2024-03-25T21:41:56.587: Found previous container 74776bbe5032 with checkpoint, ready to resume
2024-03-25T21:42:02.958: Requeue job 94p4q13abcmadfgzpxi18
2024-03-25T21:42:02.995: Found previous container 74776bbe5032 with checkpoint, ready to resume
2024-03-25T21:42:03.887: Requeue job 94p4q13abcmadfgzpxi18
2024-03-25T21:42:03.923: Found previous container 74776bbe5032 with checkpoint, ready to resume
2024-03-25T21:42:12.653: Failed to wait for workload restored on i-0baa4d7dc7a2399be, error: Failed to restore: exit status 125 (code: 9011)
2024-03-25T21:42:12.662: Failed to create new instance to recover, error: Failed to restore: exit status 125 (code: 9011)
2024-03-25T21:42:12.662: Job status changed: [Floating -> FailToComplete]
```

Restore.log.0 on instance i-0baa4d7dc7a2399be
```
(01.795003) mnt: Switching to new ns to clean ghosts
(01.795146) Unlink remap /tmp/.criu.mntns.F25b1l/14-0000000000//tmp/Rscriptdb.np9hrA.cr.1.ghost
(01.795199) Unlink remap /tmp/.criu.mntns.F25b1l/14-0000000000//tmp/Rscriptdc.J0CQSe.cr.2.ghost
(01.795339) Error (criu/cr-restore.c:2547): Restoring FAILED.
(01.795992) Error (criu/cgroup.c:1969): cg: cgroupd: recv req error: File exists
```

Restore.log.1
```
(00.355172) mnt: Switching to new ns to clean ghosts
(00.355242) Unlink remap /tmp/.criu.mntns.j32rFR/14-0000000000//tmp/Rscriptdb.np9hrA.cr.1.ghost
(00.355282) Unlink remap /tmp/.criu.mntns.j32rFR/14-0000000000//tmp/Rscriptdc.J0CQSe.cr.2.ghost
(00.355409) Error (criu/cr-restore.c:2547): Restoring FAILED.
(00.358771) Error (criu/cgroup.c:1969): cg: cgroupd: recv req error: No such file or directory
```

Restore.log.2
```
(00.499554) mnt: Switching to new ns to clean ghosts
(00.499633) Unlink remap /tmp/.criu.mntns.THDpqC/14-0000000000//tmp/Rscriptdb.np9hrA.cr.1.ghost
(00.499678) Unlink remap /tmp/.criu.mntns.THDpqC/14-0000000000//tmp/Rscriptdc.J0CQSe.cr.2.ghost
(00.499824) Error (criu/cr-restore.c:2547): Restoring FAILED.
(00.500522) Error (criu/cgroup.c:1969): cg: cgroupd: recv req error: No such file or directory
```

Here is a full list of failed jobs due to this error:

Job Link: https://23.22.157.8/#/opcenter/jobs/94p4q13abcmadfgzpxi18
Job Link: https://23.22.157.8/#/opcenter/jobs/ijnqwvookvvd5ev5pqdwy
Job Link: https://23.22.157.8/#/opcenter/jobs/9oxnfiy2ddiwrobnhjvfj
Job Link: https://23.22.157.8/#/opcenter/jobs/xfwy9u2o4hejgc8ahvfse
Job Link: https://23.22.157.8/#/opcenter/jobs/z9243zfbhbcvr5f0icwfg
Job Link: https://23.22.157.8/#/opcenter/jobs/c5p9bwrcbobzl4xwb9r59
Job Link: https://23.22.157.8/#/opcenter/jobs/ttyqoamy7a0lxuehb3po7
Job Link: https://23.22.157.8/#/opcenter/jobs/chi5sv6u9vofo7ea9fzlt
Job Link: https://23.22.157.8/#/opcenter/jobs/3s24igvc7dy9tsnpp77xh
Job Link: https://23.22.157.8/#/opcenter/jobs/xsvozuzmfztun0e3pnpip
Job Link: https://23.22.157.8/#/opcenter/jobs/t1vf7f10y4imydrniyp2i
Job Link: https://23.22.157.8/#/opcenter/jobs/ftj9dc7v0uge7q6m80b94
Job Link: https://23.22.157.8/#/opcenter/jobs/49dc1t0lwq25hhdr1om16
Job Link: https://23.22.157.8/#/opcenter/jobs/j8buhuszsyechmdu0yxp3

**Comment by Ashley-Tung** [comment]
[Update]
Code is currently being tested. Will likely be in 2.5.5

**Comment by gaow** [comment]
not sure if this is resolved but i'll close it for now, since we are no longer tracking such failures on our end now that we get support for job submissions.
