### ISSUE TITLE
Specify family types R or M in mm_jobman and jupyter_setup

### ISSUE THREAD

**Issue by gaow** [rfeng2023/mmcloud#70]
Add a switch to specify families simply R or M. Default to M. Under the hood we will use the more complicated patterns to set it for the float command. For example

```
--ec2-types R # just R
--ec2-types M # just M
--ec2-types R M # R or M both
```

**Comment by Ashley-Tung** [comment]
[Copied from Slack]
My only concern is the amount if instances there are in the r5 + r6 + r7 families, as well as the m* families, if we are to specify them all
Looking at the aws documentation (https://aws.amazon.com/ec2/instance-types/), there is easily 50+ instances to specify in each case, unless we want to limit even further

For now, the main east opcenter to set to r* types only

**Comment by Ashley-Tung** [comment]
Can we close this? I believe this ask is outdated now that we have the new setup. Additionally, while jobman has no job-level limit, interactive jobs now only have `--allowList [r5*,r6*,r7*,m*]` by default. Let me know if you think otherwise @gaow
