### ISSUE TITLE
VM policy support multiple options in mm_jobman and jupyter_setup

### ISSUE THREAD

**Issue by gaow** [rfeng2023/mmcloud#73]
@Ashley-Tung currently it seems that VM policy in mm_jobman and jupyter_setup only supports either on-demand or spot? what if I want both? That should be allowed, right?

**Comment by Ashley-Tung** [comment]
I have it set as spotOnly or onDemand as either options. If you want an option for both, we have spotFirst, which prioritizes spot instances, but can use on demand instances as well

in that case, what should the option look like? currently it is
spot -> spotOnly
ondemand -> onDemand
??? -> spotFirst

**Comment by gaow** [comment]
Thanks @Ashley-Tung that is great! sounds like it is just a matter of documentation. I think might be easier instead of figuring out our ??? we just also use spotOnly, onDemand and spotFirst, and document our default as well as available options, in the help message?

**Comment by Ashley-Tung** [comment]
got it, I can submit that change then in both the jobman and jupyter script

**Comment by Ashley-Tung** [comment]
PR submitted. If it is to your preference, we can close this issue
