### ISSUE TITLE
mm_jobman issues to be discussed or resolved

### ISSUE THREAD

**Issue by gaow** [rfeng2023/mmcloud#9]
### Allow uploading the entire folder [resolved]
Allow uploading the entire folder not contents inside of the folder. For example, currently if we do this:

```
--upload /local/output_folder:/remote
```

it's going to essentially `cp /local/output_folder/* /remote` which is not good. I want `mm_jobman.sh` to behave like this:

```
--upload /local/output_folder:/remote
```

is going to `cp -r /local/output_folder /remote`, whereas

```
--upload /local/output_folder/:/remote
```

is going to `cp -r /local/output_folder/* /remote`.

The syntax difference is if there is "`/`" at the end of local path in `--upload` command. I believe this "`/`" behavior i described is also what `rsync` does. 

Maybe `aws-cli` already provides a way to do it?

###  jupyter vm interactive session

It needs to be managed by `mm_jobman.sh`. My proposed interface is that if we don't specify a job script, its'  going to trigger a JupyterLab server with the specifications into `mm_jobman.sh`. That is, the mount, the download before the jupyter server starts, and the upload after the jupyter server is turned off.

Bottom line is that at least we will need some way to examine our results on the cloud directly. AWS charge egress to discourage it. MemVerge should not encourage it either.

###  jupyter vm as home-node

to access these jobs as well (basically as a home node/ a hub)

## Comments

1. Some results must be written directly to bucket not in VM because we need to track the results real time. We don't want to wait for a day until all jobs complete, uploaded to bucket then start checking them. Therefore for some tasks we are not going to follow the  recommendation from MemVerge team to first write to VM and copy everything to bucket after all jobs are done.

## Questions [resolved]

- How to mount buckets that are directly writable to by the analysis programs? Currently it is read-only system
- `--mountOpt "size=10"` what is this? Also mount option may have to do with above

**Comment by yiweizh-memverge** [comment]
Hi @gaow, regarding the `mountOpt` option, underlying it is the `dataVolume` option of the float executable. When using an EBS volume, `"size=10"` means creating an 10 GB EBS volume, it would be an invalid option when mounting S3 bucket, so I think you could remove it from the command (or is there any specific reason you want to keep it?). And to make it a read-and-write system, you could specify `"accesskey=xxx,secret=xxx,mode=rw"`, where accesskey and secret are the credentials of the bucket. This option would be passed to `dataVolume` option so that it could configure the bucket as read-and-write when mounting. 

Reference: [float submit cli option documentation](https://docs.memverge.com/mmce/current/userguide/olh/oxy_ex-1/topics/a_mmce_cli_summary.html#a_mmce_float_cli__submit)

**Comment by yiweizh-memverge** [comment]
Per the recursive uploading folder feature, I tried modifying the `create_upload_commands()` function to the following:
```
create_upload_commands() {
    local cmd=""
    for i in "${!upload_local[@]}"; do
        local source="${upload_local[$i]}"
        local destination="${upload_remote[$i]}"
        if [[ ${upload_local[$i]} =~ /$ ]]; then
            echo "Uploading contents inside the folder."

            # Add mkdir command for source folder if dne
            cmd+="mkdir -p $source\n"

            # Add AWS upload command
            cmd+="aws s3 sync $source s3://$destination"
            cmd+="\n"

        else
            echo "Uploading entire folder."
            local last_folder=$(basename "$source")

            # Add mkdir command for source folder if dne
            cmd+="mkdir -p $source\n"

            # Add AWS upload command
            cmd+="aws s3 sync $source s3://$destination/$last_folder"
            cmd+="\n"
        fi

    done
    # Remove the last '\n'
    cmd=${cmd%\\n}

    echo -e "$cmd"
}
```
It would check if the input has a trailing slash. If it does, then it would copy the contents inside this folder; if not, it would copy the entire folder to the destination. We could discuss about the details and test it together after @Ashley-Tung comes back from holiday.

**Comment by gaow** [comment]
> Hi @gaow, regarding the `mountOpt` option, underlying it is the `dataVolume` option of the float executable. When using an EBS volume, `"size=10"` means creating an 10 GB EBS volume, it would be an invalid option when mounting S3 bucket, so I think you could remove it from the command (or is there any specific reason you want to keep it?). And to make it a read-and-write system, you could specify `"accesskey=xxx,secret=xxx,mode=rw"`, where accesskey and secret are the credentials of the bucket. This option would be passed to `dataVolume` option so that it could configure the bucket as read-and-write when mounting.
> 
> Reference: [float submit cli option documentation](https://docs.memverge.com/mmce/current/userguide/olh/oxy_ex-1/topics/a_mmce_cli_summary.html#a_mmce_float_cli__submit)

Thanks @yiweizh-memverge in that case, we should replace the option with what's meaningful. There is no reason i want to keep it if it is wrong. I guess we need to change what this option does to make it more useful, including taking care of proper read/write privileges, and we show examples how to use this option more properly. I look forward to pull requests to address this. Thank you!

**Comment by Ashley-Tung** [comment]
Hi @gaow , to answer your question on `--mountOpt "size=10"`,  that option is equivalent to the the string array when specifying `--dataVolume` via the direct `float` cli. The help message in the CLI below shows that. To use in this way, you can specify with `--mountOpt "accesskey=xxx,secret=yyy,endpoint=zzz,mode=rw"`.
```
  -D, --dataVolume stringArray      data volumes used to run the job. Format is like this:
                                     [accesskey=xxx,secret=yyy,endpoint=zzz,mode=rw]s3://bucketname/path:/mountpoint, use S                          3 bucket, where access key and secret are optional if IAM role is used

```

I have updated it to reflect the options needed when mounting a bucket. It exists in the latest commit: https://github.com/Ashley-Tung/mmcloud_columbia/commit/77d099f107dc4832cc7f38526a232a0ed61f9d2b I believe this will no longer attach an EBS volume to your instance. It now takes in options when mounting your bucket.

This is the code section that reflects its usage:
```
# Construct dataVolume parameters
    for i in  #"${!mount_local[@]}"; do
        dataVolume_params+="--dataVolume '[$mountOpt]s3://${mount_remote[$i]}:${mount_local[$i]}' "
   
```

Additionally, we use the parameter `mode=rw` to allow read-write privileges into the bucket.

**Comment by Ashley-Tung** [comment]
If you believe we should keep the option to add an EBS volume to a directory in the instance, we can do that with a new parameter, maybe something like `--addVolume <size>`. The reason why I initially made the change was because we had no option to mount a bucket in Hui's original version
